### ISSUE TITLE
TclError when upon setting the value of the screen parsing overlay stringvar

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/gsf-parser#148]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "parsing\screen.py", line 457, in run
  File "toplevels\screenoverlay.py", line 47, in set_percentage
  File "tkinter\__init__.py", line 1345, in __setitem__
  File "tkinter\__init__.py", line 1338, in configure
  File "tkinter\__init__.py", line 1329, in _configure
_tkinter.TclError: invalid command name ".192375440.190865648"
```
This exception was caught by Tntt and is reproducable, as it keeps repeating. Other details:

Windows 10
2560x1440p resolution

**Comment by RedFantom** [comment]
This probably occurs because Tkinter is running in the other Thread and it isn't ready yet. Therefore, in line 47 of `screenoverlay.py`, an `after` command is required.
