### ISSUE TITLE
ValueError when parsing specific CombatLog

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/gsf-parser#153]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python\Python_3.5_x64\lib\tkinter\__init__.py", line 1559, in __call__
    return self.func(*args)
  File "\gsf-parser\frames\fileframe.py", line 278, in update_parse
    self.parse_file(elements[0])
  File "\gsf-parser\frames\fileframe.py", line 307, in parse_file
    enemydamaget, uncounted) = filestats.file_statistics(file_name, file_cube)
  File "\gsf-parser\parsing\filestats.py", line 82, in file_statistics
    ships_possible = parse.parse_spawn(spawn, player_list)[9]
  File "\gsf-parser\parsing\parse.py", line 341, in parse_spawn
    raise ValueError("All ships were removed, this was the last ability: {0}".format(key.strip()))
ValueError: All ships were removed, this was the last ability: Melting Hull
```

**Comment by RedFantom** [comment]
Fixed when `parser` was merged into `master` with PR #156.
