### ISSUE TITLE
GSF Parser v2.0.0 does not start on some machines

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/GSF-Parser#16]
The release version of the GSF Parser does not start on some machines with the error message "Failed to execute script main.". This is basically shorthand for: "Any error could have occurred while starting the program.". This error only occurs on some machines, and not all, so it requires further investigation. It seems Windows-version independent, as it occurs on both Windows 10 and Windows 7 machines.

**Comment by RedFantom** [comment]
Tomorrow I will investigate the issue in some VM's.

**Comment by RedFantom** [comment]
This should fix the issue. I will test it before releasing.

**Comment by RedFantom** [comment]
Fixed in version v2.0.2

**Comment by RedFantom** [comment]
On some machines running Windows 7, the error message does still display. Tested on Windows 8 VM, Windows 10 VM and Windows 7 VM, all without SWTOR or a CombatLogs folder: no issues. Further investigation is required.

**Comment by RedFantom** [comment]
Only on Windows 7 machines with the installer-version of the parser does the problem occur. Tkinter.py raises a Tkinter.TclError, because the installation of Tcl cannot be found in one of the directories where is being searched. This is a separate issue. DEBUG output:
`Traceback (most recent call last):
    File "main.py", line 18, in <module>
    File "gui.py", line 29, in __init__
    File "lib-tk\mtTkinter.py", line 138, in _Tk__init__
    File "lib-tk\Tkinter.py", line 1814, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories C:/PROGRA~2/lib/tcl8.5 {C:/Program Files (x86)/lib/tcl8.5} C:/lib/tcl8.5 {C:/Program Files (x86)/library} C:/library C:/tcl8.5.15/library C:/tcl8.5.15/library

This probably means that Tcl wasn't installed properly.

Failed to execute script main`
