### ISSUE TITLE
Invalid color name generated while parsing markers

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/gsf-parser#174]
When parsing a spawn that was parsed with screen parsing enabled, an error may occur when a spawn is parsed that results in at least one marker with an invalid color name:
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/user/Source/gsf-parser/frames/fileframe.py", line 277, in update_parse
    self.parse_spawn(elements)
  File "/home/user/Source/gsf-parser/frames/fileframe.py", line 350, in parse_spawn
    file_name, match_index, spawn_index, match_timings, spawn_timings, file_cube
  File "/home/user/Source/gsf-parser/frames/statsframe.py", line 270, in update_timeline
    self.time_line.create_marker(*args, **kwargs)
  File "/home/user/Source/gsf-parser/widgets/timeline.py", line 476, in create_marker
    width=border if border != "default" else self._marker_border
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2498, in create_rectangle
    return self._create('rectangle', args, kw)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2477, in _create
    *(args + self._options(cnf, kw))))
_tkinter.TclError: invalid color name "#cef5900"
```
It is extremely likely that these issues stem from the dynamically generated color names for the markers, possibly the markers for tracking penalty.

**Comment by RedFantom** [comment]
Fixed.
